name: Check and Build

on:
  pull_request:
    branches:
      - master
  merge_group:

jobs:
  lint:
    name: Spotless check
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Spotless
        run: ./gradlew spotlessCheck

  build:
    needs: lint
    if: ${{ needs.lint.result == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew buildDevDebug
